const units = [
  {
    id: "a1-unit4",
    name: "A1 — Unit 4",
    sections: [
      {
        name: "Time Expressions",
        questions: [
          { question: "_____ arkadaşlarımla piknik yaptık.", options: ["Bugüne kadar hiç", "Bir hafta önce", "Bugüne kadar", "Geçen sene"], correct: 1 },
          { question: "_____ yurt dışına çıktın mı?", options: ["Az önce", "Bugüne kadar", "Bu yıl", "Geçen sene"], correct: 1 },
          { question: "_____ buraya yerleştik.", options: ["Bu sabah", "Az önce", "Geçen sene", "Bugüne kadar hiç"], correct: 2 },
          { question: "_____ üniversiteden mezun oldular.", options: ["Bu yıl", "Az önce", "Bugüne kadar", "Bugüne kadar hiç"], correct: 0 },
          { question: "_____ kuzenime uğradım.", options: ["Bugüne kadar hiç", "Dün", "Bugüne kadar", "Bu yıl"], correct: 1 },
          { question: "_____ büyük bir gürültüyle uyandık.", options: ["Geçen sene", "Bugüne kadar", "Bu sabah", "Bir hafta önce"], correct: 2 },
          { question: "_____ arabamı tamir ettim.", options: ["Bugüne kadar hiç", "Önceki gün", "Geçen sene", "Bugüne kadar"], correct: 1 },
          { question: "_____ böyle bir insanla tanışmadım.", options: ["Az önce", "Dün", "Bugüne kadar hiç", "Bu sabah"], correct: 2 },
          { question: "_____ akşam tatilden döndük.", options: ["Bugün", "Bugüne kadar hiç", "Bu yıl", "Bugüne kadar"], correct: 0 },
          { question: "_____ elektrikler kesildi.", options: ["Geçen sene", "Bu yıl", "Az önce", "Bugüne kadar"], correct: 2 },
        ],
      },
      {
        name: "Verb Conjugation",
        questions: [
          { question: "Amcam dün Almanya'ya _____.", options: ["gittim", "gitti", "gittik", "gittiniz"], correct: 1 },
          { question: "Biz geçen yıl tatile _____.", options: ["çıktı", "çıktım", "çıktık", "çıktınız"], correct: 2 },
          { question: "Ben 1968'de Trabzon'da _____.", options: ["doğdu", "doğduk", "doğdum", "doğdunuz"], correct: 2 },
          { question: "Dün hiç yemek _____.", options: ["yedim", "yemedim", "yemedi", "yemedik"], correct: 1 },
          { question: "Paranızı nerede _____?", options: ["kaybettim", "kaybetti", "kaybettik", "kaybettiniz"], correct: 3 },
          { question: "Dün seni çok _____. Neredeydin?", options: ["aradı", "aradık", "aradım", "aradınız"], correct: 2 },
          { question: "Siz geçen haftaki konsere _____?", options: ["gittim mi", "gitti mi", "gittiniz mi", "gittik mi"], correct: 2 },
          { question: "Biraz önce annem telefon _____.", options: ["ettim", "etti", "ettik", "ettiniz"], correct: 1 },
          { question: "Sen dün akşam ödev _____?", options: ["yapmadım mı", "yapmadın mı", "yapmadı mı", "yapmadık mı"], correct: 1 },
          { question: "Geçen hafta sınava _____.", options: ["girmedi", "girmedik", "girmedim", "girmediniz"], correct: 2 },
        ],
      },
      {
        name: "Match the Question",
        questions: [
          { question: "B: Dün sinemaya gittim. — Which question was asked?", options: ["Dün nereye gittin?", "Dün kiminle gittin?", "Dün ne zaman gittin?", "Dün nasıl gittin?"], correct: 0 },
          { question: "B: Bugün çarşıdan 1 kilo portakal ve 2 kilo elma aldım. — Which question was asked?", options: ["Bugün nereye gittin?", "Bugün ne zaman çarşıya gittin?", "Bugün çarşıdan ne aldın?", "Bugün kiminle çarşıya gittin?"], correct: 2 },
          { question: "B: Dün akşam balık lokantasında güzel bir yemek yedik. — Which question was asked?", options: ["Dün akşam ne yediniz?", "Dün akşam kiminle yediniz?", "Dün akşam ne zaman yediniz?", "Dün akşam nerede yemek yediniz?"], correct: 3 },
          { question: "B: Ali geçen yıl üniversiteden mezun oldu. — Which question was asked?", options: ["Ali nerede okudu?", "Ali ne zaman üniversiteden mezun oldu?", "Ali nasıl mezun oldu?", "Ali kiminle mezun oldu?"], correct: 1 },
        ],
      },
      {
        name: "Synonyms",
        questions: [
          { question: "\"Acılar\" (ağrılar, üzüntüler) ile eş anlamlı kelime hangisidir?", options: ["mutluluklar", "sıkıntılar", "hayaller", "düşünceler"], correct: 1 },
          { question: "\"İlgilenmek\" (meşgul olmak) ile eş anlamlı kelime hangisidir?", options: ["dinlenmek", "beklemek", "uğraşmak", "başlamak"], correct: 2 },
        ],
      },
      {
        name: "Past Tense Suffixes",
        questions: [
          { question: "Geçen yaz tatilde Alanya'_____, hava çok güzel_____.", options: ["daydık ... güzeldi", "daydı ... güzeldi", "daydım ... güzeldim", "daydınız ... güzeldiniz"], correct: 0 },
          { question: "Üniversitede hiç çalışkan bir öğrenci _____.", options: ["değildim", "değildi", "değildik", "değildiniz"], correct: 1 },
          { question: "Geçen ay kızım doğum yaptı ve ben dede _____.", options: ["oldu", "oldum", "olduk", "oldunuz"], correct: 1 },
          { question: "Tatilin nasıl geçti? Otel kalabalık _____?", options: ["mıydım", "mıydı", "mıydık", "mıydınız"], correct: 1 },
          { question: "Sen dün evde yok _____?", options: ["muydum", "muydun", "muydu", "muyduk"], correct: 1 },
          { question: "Tarkan ilk şarkısıyla çok meşhur_____.", options: ["dum", "du", "duk", "dunuz"], correct: 1 },
          { question: "Dün akşam seni aradım. Evde yoktun. Nerede_____?", options: ["ydim", "ydin", "ydi", "ydik"], correct: 1 },
        ],
      },
      {
        name: "Correct Sentence",
        questions: [
          { question: "Hangisi doğru? (geçen kış → past tense)", options: ["Geçen kış hava çok soğuk.", "Geçen kış hava çok soğuktu.", "Geçen kış hava çok soğuktur.", "Geçen kış hava çok soğuk olur."], correct: 1 },
          { question: "Hangisi doğru? (iki yıl önce → past tense)", options: ["Serap iki yıl önce öğrenci.", "Serap iki yıl önce öğrencidir.", "Serap iki yıl önce öğrenciydi.", "Serap iki yıl önce öğrenciymi."], correct: 2 },
          { question: "Hangisi doğru? (dün akşam → past tense)", options: ["Dün akşam neredesin?", "Dün akşam neredeydin?", "Dün akşam neredesiniz?", "Dün akşam nerdedir?"], correct: 1 },
          { question: "Hangisi doğru? (geçen hafta → past tense)", options: ["Geçen hafta hava güneşli.", "Geçen hafta hava güneşlidir.", "Geçen hafta hava güneşliydi.", "Geçen hafta hava güneşliyor."], correct: 2 },
          { question: "Hangisi doğru? (dün → past, şimdi → present)", options: ["Dün hastayım, şimdi iyiyim.", "Dün hastaydım, şimdi iyiydim.", "Dün hastaydım, şimdi iyiyim.", "Dün hastayım, şimdi iyiydim."], correct: 2 },
        ],
      },
      {
        name: "Past Habitual vs Present",
        questions: [
          { question: "Çocukluğumu çok iyi _____. (narrator remembers now)", options: ["hatırlıyorum", "hatırlıyordum"], correct: 0 },
          { question: "Yazları köyde güzel vakit _____. (habitual past)", options: ["geçirdik", "geçiriyorduk"], correct: 1 },
          { question: "Her gün dışarıda _____. (habitual past)", options: ["oynadık", "oynuyorduk"], correct: 1 },
          { question: "Her hafta sonu nehire _____. (habitual past)", options: ["gittik", "gidiyorduk"], correct: 1 },
          { question: "Teknoloji şimdi insanları _____. (now)", options: ["yalnızlaştırıyor", "yalnızlaştırıyordu"], correct: 0 },
          { question: "Gençler şimdi zamanlarını internette _____. (now)", options: ["geçiriyorlar", "geçiriyorlardı"], correct: 0 },
          { question: "Bizim zamanımızda akşamları _____. (habitual past)", options: ["toplandık", "toplanıyorduk"], correct: 1 },
          { question: "Hep birlikte sohbet _____. (habitual past)", options: ["ettik", "ediyorduk"], correct: 1 },
          { question: "Birbirimize hikayeler _____. (habitual past)", options: ["anlattık", "anlatıyorduk"], correct: 1 },
          { question: "Hep birlikte _____. (habitual past)", options: ["eğlendik", "eğleniyorduk"], correct: 1 },
          { question: "Şimdi insanlar fast food _____. (now)", options: ["yiyorlar", "yiyorlardı"], correct: 0 },
          { question: "Şimdi insanlar birbirleriyle _____. (now)", options: ["konuşmuyorlar", "konuşmuyorlardı"], correct: 0 },
          { question: "Şimdi kimse dışarı çıkmak _____. (now)", options: ["istemiyorlar", "istemiyorlardı"], correct: 0 },
          { question: "Ben eskiden her şeyin daha güzel olduğunu _____. (narrator thinks now)", options: ["düşünüyorum", "düşünüyordum"], correct: 0 },
        ],
      },
      {
        name: "-(y)ken Suffixes",
        questions: [
          { question: "Saçların uzun_____ daha güzel_____. Niçin kestirdin?", options: ["ken ... di", "ken ... dı", "dayken ... du", "yken ... dı"], correct: 0 },
          { question: "Sen banyo_____ bir arkadaşın ara_____, ama adını söyle_____.", options: ["dayken ... dı ... medi", "deyken ... di ... medi", "dayken ... di ... medi", "deyken ... dı ... medi"], correct: 0 },
          { question: "Ben beş yaşında_____ bale kursuna git_____.", options: ["yken ... tim", "yken ... tım", "ken ... dim", "yken ... dim"], correct: 0 },
          { question: "Müdür Bey, siz toplantı_____ misafiriniz gel_____.", options: ["dayken ... di", "deyken ... di", "dayken ... dı", "deyken ... dı"], correct: 0 },
          { question: "Ben küçük_____ annem çalış_____. Bu nedenle bana anneannem bak_____.", options: ["ken ... ıyordu ... ıyordu", "ken ... iyordu ... iyordu", "ken ... ıyordu ... iyordu", "dayken ... ıyordu ... ıyordu"], correct: 0 },
          { question: "Ayşe Hanım, siz tatil_____ komşunun evine hırsız gir_____.", options: ["deyken ... miş", "dayken ... mış", "deyken ... mış", "dayken ... miş"], correct: 0 },
          { question: "Sen yok_____ cep telefonun çaldı.", options: ["ken", "dayken", "yken", "iken"], correct: 0 },
          { question: "Ben üniversite_____ dans kursuna git_____.", options: ["deyken ... tim", "dayken ... tım", "deyken ... dim", "dayken ... tim"], correct: 0 },
        ],
      },
      {
        name: "Instrumental Case (-le/-la)",
        questions: [
          { question: "Bu mektubu senin _____ yazdım.", options: ["kalemin", "kaleminle", "kalemde", "kaleme"], correct: 1 },
          { question: "Uçakta _____ konuşmak yasak.", options: ["cep telefonunda", "cep telefonuyla", "cep telefonunu", "cep telefonuna"], correct: 1 },
          { question: "Saçlarını bu _____ mı tarıyorsun?", options: ["tarağı", "tarakta", "tarakla", "tarağa"], correct: 2 },
          { question: "Üç boyutlu filmleri özel bir _____ izliyoruz.", options: ["gözlüğü", "gözlükte", "gözlüğe", "gözlükle"], correct: 3 },
          { question: "Bu yemeği _____ yememek gerek.", options: ["çatalı", "çatala", "çatalla", "çatalda"], correct: 2 },
        ],
      },
      {
        name: "With (-le/-la) Dialogues",
        questions: [
          { question: "A: Öğrenciler okula nasıl gidiyorlar? B: Otobüs_____.", options: ["le", "la", "de", "te"], correct: 0 },
          { question: "A: Sınıfta kimler var? B: Öğretmen_____ öğrenciler.", options: ["la", "le", "de", "dan"], correct: 1 },
          { question: "A: Kim_____ ders çalışıyorsun? B: Yalnız çalışıyorum.", options: ["la", "le", "de", "den"], correct: 1 },
          { question: "A: Dün ne yaptın? B: Arkadaşım_____ sinemaya gittim.", options: ["le", "la", "dan", "da"], correct: 1 },
          { question: "A: Dilek Murat_____ ne zaman evleniyor? B: Sanırım gelecek ay.", options: ["'le", "'la", "'dan", "'ta"], correct: 1 },
          { question: "A: Alo. Deniz_____ mi görüşüyorum? B: Evet, buyrun ben Deniz.", options: ["'la", "'le", "'den", "'de"], correct: 1 },
        ],
      },
    ],
  },
];
