const units = [
  {
    id: "a1-unit4",
    name: "A1 — Unit 4",
    sections: [
      {
        name: "Time Expressions",
        questions: [
          { question: "_____ arkadaşlarımla piknik yaptık.", options: ["Bugüne kadar hiç", "Bir hafta önce", "Bugüne kadar", "Geçen sene"], correct: 1 },
          { question: "_____ yurt dışına çıktın mı?", options: ["Az önce", "Bugüne kadar", "Bu yıl", "Geçen sene"], correct: 1 },
          { question: "_____ buraya yerleştik.", options: ["Bu sabah", "Az önce", "Geçen sene", "Bugüne kadar hiç"], correct: 2 },
          { question: "_____ üniversiteden mezun oldular.", options: ["Bu yıl", "Az önce", "Bugüne kadar", "Bugüne kadar hiç"], correct: 0 },
          { question: "_____ kuzenime uğradım.", options: ["Bugüne kadar hiç", "Dün", "Bugüne kadar", "Bu yıl"], correct: 1 },
          { question: "_____ büyük bir gürültüyle uyandık.", options: ["Geçen sene", "Bugüne kadar", "Bu sabah", "Bir hafta önce"], correct: 2 },
          { question: "_____ arabamı tamir ettim.", options: ["Bugüne kadar hiç", "Önceki gün", "Geçen sene", "Bugüne kadar"], correct: 1 },
          { question: "_____ böyle bir insanla tanışmadım.", options: ["Az önce", "Dün", "Bugüne kadar hiç", "Bu sabah"], correct: 2 },
          { question: "_____ akşam tatilden döndük.", options: ["Bugün", "Bugüne kadar hiç", "Bu yıl", "Bugüne kadar"], correct: 0 },
          { question: "_____ elektrikler kesildi.", options: ["Geçen sene", "Bu yıl", "Az önce", "Bugüne kadar"], correct: 2 },
        ],
      },
      {
        name: "Verb Conjugation",
        questions: [
          { question: "Amcam dün Almanya'ya _____.", options: ["gittim", "gitti", "gittik", "gittiniz"], correct: 1 },
          { question: "Biz geçen yıl tatile _____.", options: ["çıktı", "çıktım", "çıktık", "çıktınız"], correct: 2 },
          { question: "Ben 1968'de Trabzon'da _____.", options: ["doğdu", "doğduk", "doğdum", "doğdunuz"], correct: 2 },
          { question: "Dün hiç yemek _____.", options: ["yedim", "yemedim", "yemedi", "yemedik"], correct: 1 },
          { question: "Paranızı nerede _____?", options: ["kaybettim", "kaybetti", "kaybettik", "kaybettiniz"], correct: 3 },
          { question: "Dün seni çok _____. Neredeydin?", options: ["aradı", "aradık", "aradım", "aradınız"], correct: 2 },
          { question: "Siz geçen haftaki konsere _____?", options: ["gittim mi", "gitti mi", "gittiniz mi", "gittik mi"], correct: 2 },
          { question: "Biraz önce annem telefon _____.", options: ["ettim", "etti", "ettik", "ettiniz"], correct: 1 },
          { question: "Sen dün akşam ödev _____?", options: ["yapmadım mı", "yapmadın mı", "yapmadı mı", "yapmadık mı"], correct: 1 },
          { question: "Geçen hafta sınava _____.", options: ["girmedi", "girmedik", "girmedim", "girmediniz"], correct: 2 },
        ],
      },
      {
        name: "Match the Question",
        questions: [
          { question: "B: Dün sinemaya gittim. — Which question was asked?", options: ["Dün nereye gittin?", "Dün kiminle gittin?", "Dün ne zaman gittin?", "Dün nasıl gittin?"], correct: 0 },
          { question: "B: Bugün çarşıdan 1 kilo portakal ve 2 kilo elma aldım. — Which question was asked?", options: ["Bugün nereye gittin?", "Bugün ne zaman çarşıya gittin?", "Bugün çarşıdan ne aldın?", "Bugün kiminle çarşıya gittin?"], correct: 2 },
          { question: "B: Dün akşam balık lokantasında güzel bir yemek yedik. — Which question was asked?", options: ["Dün akşam ne yediniz?", "Dün akşam kiminle yediniz?", "Dün akşam ne zaman yediniz?", "Dün akşam nerede yemek yediniz?"], correct: 3 },
          { question: "B: Ali geçen yıl üniversiteden mezun oldu. — Which question was asked?", options: ["Ali nerede okudu?", "Ali ne zaman üniversiteden mezun oldu?", "Ali nasıl mezun oldu?", "Ali kiminle mezun oldu?"], correct: 1 },
        ],
      },
      {
        name: "Synonyms",
        questions: [
          { question: "\"Acılar\" (ağrılar, üzüntüler) ile eş anlamlı kelime hangisidir?", options: ["mutluluklar", "sıkıntılar", "hayaller", "düşünceler"], correct: 1 },
          { question: "\"İlgilenmek\" (meşgul olmak) ile eş anlamlı kelime hangisidir?", options: ["dinlenmek", "beklemek", "uğraşmak", "başlamak"], correct: 2 },
        ],
      },
      {
        name: "Past Tense Suffixes",
        questions: [
          { question: "Geçen yaz tatilde Alanya'_____, hava çok güzel_____.", options: ["daydık ... güzeldi", "daydı ... güzeldi", "daydım ... güzeldim", "daydınız ... güzeldiniz"], correct: 0 },
          { question: "Üniversitede hiç çalışkan bir öğrenci _____.", options: ["değildim", "değildi", "değildik", "değildiniz"], correct: 1 },
          { question: "Geçen ay kızım doğum yaptı ve ben dede _____.", options: ["oldu", "oldum", "olduk", "oldunuz"], correct: 1 },
          { question: "Tatilin nasıl geçti? Otel kalabalık _____?", options: ["mıydım", "mıydı", "mıydık", "mıydınız"], correct: 1 },
          { question: "Sen dün evde yok _____?", options: ["muydum", "muydun", "muydu", "muyduk"], correct: 1 },
          { question: "Tarkan ilk şarkısıyla çok meşhur_____.", options: ["dum", "du", "duk", "dunuz"], correct: 1 },
          { question: "Dün akşam seni aradım. Evde yoktun. Nerede_____?", options: ["ydim", "ydin", "ydi", "ydik"], correct: 1 },
        ],
      },
      {
        name: "Correct Sentence",
        questions: [
          { question: "Hangisi doğru? (geçen kış → past tense)", options: ["Geçen kış hava çok soğuk.", "Geçen kış hava çok soğuktu.", "Geçen kış hava çok soğuktur.", "Geçen kış hava çok soğuk olur."], correct: 1 },
          { question: "Hangisi doğru? (iki yıl önce → past tense)", options: ["Serap iki yıl önce öğrenci.", "Serap iki yıl önce öğrencidir.", "Serap iki yıl önce öğrenciydi.", "Serap iki yıl önce öğrenciymi."], correct: 2 },
          { question: "Hangisi doğru? (dün akşam → past tense)", options: ["Dün akşam neredesin?", "Dün akşam neredeydin?", "Dün akşam neredesiniz?", "Dün akşam nerdedir?"], correct: 1 },
          { question: "Hangisi doğru? (geçen hafta → past tense)", options: ["Geçen hafta hava güneşli.", "Geçen hafta hava güneşlidir.", "Geçen hafta hava güneşliydi.", "Geçen hafta hava güneşliyor."], correct: 2 },
          { question: "Hangisi doğru? (dün → past, şimdi → present)", options: ["Dün hastayım, şimdi iyiyim.", "Dün hastaydım, şimdi iyiydim.", "Dün hastaydım, şimdi iyiyim.", "Dün hastayım, şimdi iyiydim."], correct: 2 },
        ],
      },
      {
        name: "Past Habitual vs Present",
        questions: [
          { question: "Çocukluğumu çok iyi _____. (narrator remembers now)", options: ["hatırlıyorum", "hatırlıyordum"], correct: 0 },
          { question: "Yazları köyde güzel vakit _____. (habitual past)", options: ["geçirdik", "geçiriyorduk"], correct: 1 },
          { question: "Her gün dışarıda _____. (habitual past)", options: ["oynadık", "oynuyorduk"], correct: 1 },
          { question: "Her hafta sonu nehire _____. (habitual past)", options: ["gittik", "gidiyorduk"], correct: 1 },
          { question: "Teknoloji şimdi insanları _____. (now)", options: ["yalnızlaştırıyor", "yalnızlaştırıyordu"], correct: 0 },
          { question: "Gençler şimdi zamanlarını internette _____. (now)", options: ["geçiriyorlar", "geçiriyorlardı"], correct: 0 },
          { question: "Bizim zamanımızda akşamları _____. (habitual past)", options: ["toplandık", "toplanıyorduk"], correct: 1 },
          { question: "Hep birlikte sohbet _____. (habitual past)", options: ["ettik", "ediyorduk"], correct: 1 },
          { question: "Birbirimize hikayeler _____. (habitual past)", options: ["anlattık", "anlatıyorduk"], correct: 1 },
          { question: "Hep birlikte _____. (habitual past)", options: ["eğlendik", "eğleniyorduk"], correct: 1 },
          { question: "Şimdi insanlar fast food _____. (now)", options: ["yiyorlar", "yiyorlardı"], correct: 0 },
          { question: "Şimdi insanlar birbirleriyle _____. (now)", options: ["konuşmuyorlar", "konuşmuyorlardı"], correct: 0 },
          { question: "Şimdi kimse dışarı çıkmak _____. (now)", options: ["istemiyorlar", "istemiyorlardı"], correct: 0 },
          { question: "Ben eskiden her şeyin daha güzel olduğunu _____. (narrator thinks now)", options: ["düşünüyorum", "düşünüyordum"], correct: 0 },
        ],
      },
      {
        name: "-(y)ken Suffixes",
        questions: [
          { question: "Saçların uzun_____ daha güzel_____. Niçin kestirdin?", options: ["ken ... di", "ken ... dı", "dayken ... du", "yken ... dı"], correct: 0 },
          { question: "Sen banyo_____ bir arkadaşın ara_____, ama adını söyle_____.", options: ["dayken ... dı ... medi", "deyken ... di ... medi", "dayken ... di ... medi", "deyken ... dı ... medi"], correct: 0 },
          { question: "Ben beş yaşında_____ bale kursuna git_____.", options: ["yken ... tim", "yken ... tım", "ken ... dim", "yken ... dim"], correct: 0 },
          { question: "Müdür Bey, siz toplantı_____ misafiriniz gel_____.", options: ["dayken ... di", "deyken ... di", "dayken ... dı", "deyken ... dı"], correct: 0 },
          { question: "Ben küçük_____ annem çalış_____. Bu nedenle bana anneannem bak_____.", options: ["ken ... ıyordu ... ıyordu", "ken ... iyordu ... iyordu", "ken ... ıyordu ... iyordu", "dayken ... ıyordu ... ıyordu"], correct: 0 },
          { question: "Ayşe Hanım, siz tatil_____ komşunun evine hırsız gir_____.", options: ["deyken ... miş", "dayken ... mış", "deyken ... mış", "dayken ... miş"], correct: 0 },
          { question: "Sen yok_____ cep telefonun çaldı.", options: ["ken", "dayken", "yken", "iken"], correct: 0 },
          { question: "Ben üniversite_____ dans kursuna git_____.", options: ["deyken ... tim", "dayken ... tım", "deyken ... dim", "dayken ... tim"], correct: 0 },
        ],
      },
      {
        name: "Instrumental Case (-le/-la)",
        questions: [
          { question: "Bu mektubu senin _____ yazdım.", options: ["kalemin", "kaleminle", "kalemde", "kaleme"], correct: 1 },
          { question: "Uçakta _____ konuşmak yasak.", options: ["cep telefonunda", "cep telefonuyla", "cep telefonunu", "cep telefonuna"], correct: 1 },
          { question: "Saçlarını bu _____ mı tarıyorsun?", options: ["tarağı", "tarakta", "tarakla", "tarağa"], correct: 2 },
          { question: "Üç boyutlu filmleri özel bir _____ izliyoruz.", options: ["gözlüğü", "gözlükte", "gözlüğe", "gözlükle"], correct: 3 },
          { question: "Bu yemeği _____ yememek gerek.", options: ["çatalı", "çatala", "çatalla", "çatalda"], correct: 2 },
        ],
      },
      {
        name: "With (-le/-la) Dialogues",
        questions: [
          { question: "A: Öğrenciler okula nasıl gidiyorlar? B: Otobüs_____.", options: ["le", "la", "de", "te"], correct: 0 },
          { question: "A: Sınıfta kimler var? B: Öğretmen_____ öğrenciler.", options: ["la", "le", "de", "dan"], correct: 1 },
          { question: "A: Kim_____ ders çalışıyorsun? B: Yalnız çalışıyorum.", options: ["la", "le", "de", "den"], correct: 1 },
          { question: "A: Dün ne yaptın? B: Arkadaşım_____ sinemaya gittim.", options: ["le", "la", "dan", "da"], correct: 1 },
          { question: "A: Dilek Murat_____ ne zaman evleniyor? B: Sanırım gelecek ay.", options: ["'le", "'la", "'dan", "'ta"], correct: 1 },
          { question: "A: Alo. Deniz_____ mi görüşüyorum? B: Evet, buyrun ben Deniz.", options: ["'la", "'le", "'den", "'de"], correct: 1 },
        ],
      },
    ],
  },
  {
    id: "a1-unit5",
    name: "A1 — Unit 5",
    sections: [
      {
        name: "Bir Şey Lazım mı?",
        questions: [
          { question: "Eren: Markete _____ ? Birşey lazım mı?", options: ["uğra", "uğrayayım mı", "alayım mı", "etme"], correct: 1 },
          { question: "Mert: Evet Erenciğim, lütfen _____.", options: ["al", "uğrayayım mı", "uğra", "tamamla"], correct: 2 },
          { question: "Mert: Bence sen birkaç tane de meyve suyu ve bira _____.", options: ["alayım", "almasın", "al", "yiyelim"], correct: 2 },
          { question: "Volkan: Meyve suyu _____, ben aldım.", options: ["alayım mı", "al", "almasın", "yapsın"], correct: 2 },
          { question: "Mert: Eren, Volkan meyve suyu _____ diyor.", options: ["alayım", "al", "etme", "almasın"], correct: 3 },
          { question: "Eren: Peki, o zaman yiyecek bir şeyler _____ ? Cips, çikolata...", options: ["alayım mı", "almasın", "tamamla", "uğrayayım mı"], correct: 0 },
          { question: "Mert: Cips aldım ama çikolata da iyi fikir. Sen bana çikolata _____.", options: ["alayım", "almasın", "al", "yapsın"], correct: 2 },
          { question: "Eren: Tamam, sana çikolata _____, ama benim karnım aç.", options: ["al", "alayım", "almasın", "alayım mı"], correct: 1 },
          { question: "Eren: Volkan bize güzel bir makarna _____.", options: ["hazırlayayım", "yiyelim", "yapsın", "tamamla"], correct: 2 },
          { question: "Mert: Ben de acıktım şimdi. Ben sofrayı _____.", options: ["tamamla", "hazırlayayım", "yiyelim", "yapsın"], correct: 1 },
          { question: "Mert: Haydi sen de çabuk _____ !", options: ["etme", "al", "ol", "uğra"], correct: 2 },
          { question: "Mert: Alışverişi _____ da bir an önce yemek _____.", options: ["tamamla ... yiyelim", "etme ... yapsın", "al ... alayım", "ol ... hazırlayayım"], correct: 0 },
          { question: "Eren: Tamam tamam! Acele _____.", options: ["ol", "tamamla", "etme", "al"], correct: 2 },
        ],
      },
      {
        name: "Imperative Suffixes",
        questions: [
          { question: "Burcu'ya söyle, ödevini hemen bitir____.", options: ["-sin", "-alım", "-me", "-ın"], correct: 0 },
          { question: "Çok yorulduk, haydi biraz dinlen____.", options: ["-sin", "-me", "-elim", "-in"], correct: 2 },
          { question: "Öğretmen kızıyor, bir daha geç kal____.", options: ["-sın", "-ma", "-alım", "-ın"], correct: 1 },
          { question: "Bugün hava güzel, şemsiyeni al____.", options: ["-ın", "-sın", "-ma", "-ayım"], correct: 2 },
          { question: "Bu akşam yemek için dışarı çık____ ____?", options: ["-sın mı", "-ma mı", "-alım mı", "-ın mı"], correct: 2 },
          { question: "Teneffüste çay iç____.", options: ["-sin", "-me", "-in", "-elim"], correct: 3 },
          { question: "Kaçta çıkıyorsun? Seni işten al____ ____?", options: ["-alım mı", "-ayım mı", "-sın mı", "-ma mı"], correct: 1 },
          { question: "Tok musun? Yemek yap____ ____?", options: ["-sın mı", "-alım mı", "-ayım mı", "-ma mı"], correct: 2 },
          { question: "Lütfen odada sigara iç____.", options: ["-sin", "-elim", "-in", "-me"], correct: 3 },
          { question: "Sınav kağıdına mutlaka adınızı yaz____.", options: ["-ma", "-ın", "-sın", "-alım"], correct: 1 },
        ],
      },
      {
        name: "Measure Words (Miktar Sözcükleri)",
        questions: [
          { question: "Bir ____ süt.", options: ["litre", "kutu", "bardak", "paket"], correct: 1 },
          { question: "Bir ____ vişne.", options: ["dilim", "tane", "kilo", "avuç"], correct: 2 },
          { question: "Bir ____ meyve suyu.", options: ["kadeh", "kutu", "litre", "fiske"], correct: 2 },
          { question: "Bir ____ ekmek.", options: ["parça", "kalıp", "paket", "dilim"], correct: 3 },
          { question: "Bir ____ elma.", options: ["tane", "kilo", "dilim", "avuç"], correct: 0 },
          { question: "Bir ____ havuç.", options: ["demet", "kilogram", "parça", "tane"], correct: 1 },
          { question: "Dört ____ yumurta.", options: ["dilim", "kilo", "adet", "avuç"], correct: 2 },
          { question: "Dört ____ dondurma.", options: ["kutu", "parça", "tane", "top"], correct: 3 },
          { question: "Bir ____ fındık.", options: ["paket", "avuç", "kilo", "tane"], correct: 1 },
          { question: "Bir ____ yoğurt.", options: ["bardak", "dilim", "kadeh", "fiske"], correct: 0 },
          { question: "Bir ____ peynir.", options: ["dilim", "kalıp", "parça", "gram"], correct: 1 },
          { question: "Bir ____ tuz.", options: ["paket", "avuç", "fiske", "gram"], correct: 2 },
          { question: "Bir ____ üzüm.", options: ["kilo", "tane", "salkım", "avuç"], correct: 2 },
          { question: "Bir ____ maydanoz.", options: ["salkım", "demet", "avuç", "parça"], correct: 1 },
          { question: "Bir ____ biftek.", options: ["kalıp", "dilim", "parça", "kilogram"], correct: 2 },
          { question: "Bir ____ şarap.", options: ["bardak", "litre", "kutu", "kadeh"], correct: 3 },
          { question: "Bir ____ kola.", options: ["kutu", "bardak", "litre", "kadeh"], correct: 0 },
          { question: "Bir ____ makarna.", options: ["kilo", "parça", "paket", "kutu"], correct: 2 },
        ],
      },
      {
        name: "Cooking Verbs (Pişirme Fiilleri)",
        questions: [
          { question: "Annem diyet yapıyor. Sebzeleri suda ____ ve yağsız yiyor.", options: ["kızartıyor", "haşlıyor", "rendeliyor", "çırpıyor"], correct: 1 },
          { question: "Sen köfte yap, ben de patates ____.", options: ["kızartayım", "kaynatayım", "rendeleyeyim", "süzeyim"], correct: 0 },
          { question: "Kızım, salata yapmak için domates ____ ve havuç ____.", options: ["kaynat / süz", "doğra / rendele", "böl / karıştır", "çırp / kızart"], correct: 1 },
          { question: "Hülya makarna için önce suyu ____, piştikten sonra süzgeçle ____.", options: ["karıştır / böl", "çırp / rendele", "kaynat / süz", "kızart / doğra"], correct: 2 },
          { question: "Bu sandviç bana çok fazla. İkiye ____, yarısını sen ye.", options: ["doğra", "rendele", "böl", "karıştır"], correct: 2 },
          { question: "Ablam kek için önce yumurta ve şekeri ____.", options: ["rendeliyor", "süzüyor", "doğruyor", "çırpıyor"], correct: 3 },
          { question: "Çayına şeker koymadım, sen koy ve ____.", options: ["süz", "karıştır", "rendele", "kaynat"], correct: 1 },
          { question: "Akşama misafirimiz var, yemeğe ne ____?", options: ["rendeleyeyim", "süzeyim", "pişireyim", "kaynatayım"], correct: 2 },
        ],
      },
      {
        name: "-lı/-li/-sız/-siz Suffixes",
        questions: [
          { question: "İki oda____, mobilya____ bir ev arıyorum.", options: ["-lı, -lı", "-sız, -sız", "-lı, -sız", "-sız, -lı"], correct: 0 },
          { question: "Babam şeker____ çay içiyor, çünkü tatlı sevmiyor.", options: ["-li", "-siz", "-lı", "-süz"], correct: 1 },
          { question: "Benim arabam klima____.", options: ["-sız", "-siz", "-lı", "-lü"], correct: 2 },
          { question: "Onun babası iyi kalp____ bir adam.", options: ["-siz", "-li", "-lı", "-sız"], correct: 1 },
          { question: "Süt____ kahve istiyor musun?", options: ["-suz", "-süz", "-lü", "-lı"], correct: 2 },
          { question: "Hava çok rüzgar____, zor yürüyorum.", options: ["-sız", "-lı", "-li", "-siz"], correct: 1 },
          { question: "Ahmet çok akıl____ bir çocuk. Her şeyi çok çabuk öğreniyor.", options: ["-sız", "-lü", "-lı", "-lı"], correct: 2 },
          { question: "Denge____ beslenmek çok önemli.", options: ["-siz", "-li", "-lü", "-süz"], correct: 1 },
          { question: "Mavi göz____ kız bana bakıyor.", options: ["-süz", "-li", "-lü", "-suz"], correct: 2 },
          { question: "Kafein____ kahveyi çok seviyorum. Çünkü daha sağlıklı.", options: ["-li", "-lı", "-sız", "-siz"], correct: 3 },
        ],
      },
      {
        name: "Opposites (Zıt Anlamlar)",
        questions: [
          { question: "\"Evli\"nin zıt anlamlısı nedir?", options: ["Evsiz", "Bekar"], correct: 1 },
          { question: "\"Bulutlu\"nun zıt anlamlısı nedir?", options: ["Bulutsuz", "Açık"], correct: 1 },
          { question: "\"Düzenli\"nin zıt anlamlısı nedir?", options: ["Düzensiz", "Dağınık"], correct: 1 },
          { question: "\"Hızlı\"nın zıt anlamlısı nedir?", options: ["Hızsız", "Yavaş"], correct: 1 },
          { question: "\"Pahalı\"nın zıt anlamlısı nedir?", options: ["Pahasız", "Ucuz"], correct: 1 },
          { question: "\"Sinirli\"nin zıt anlamlısı nedir?", options: ["Sinirsiz", "Sakin"], correct: 1 },
          { question: "\"Kilolu\"nun zıt anlamlısı nedir?", options: ["Kilosuz", "Zayıf"], correct: 1 },
          { question: "\"Yaşlı\"nın zıt anlamlısı nedir?", options: ["Yaşsız", "Genç"], correct: 1 },
          { question: "\"Sütlü\"nün zıt anlamlısı nedir?", options: ["Sütsüz", "Sade"], correct: 1 },
          { question: "\"Kirli\"nin zıt anlamlısı nedir?", options: ["Kirsiz", "Temiz"], correct: 1 },
        ],
      },
      {
        name: "Shopping & Payment (Alışveriş ve Ödeme)",
        questions: [
          { question: "Satıcı: 80 TL efendim. Ama ____ ödemelerde %20 indirim var.", options: ["nakit", "peşin", "taksitli", "kredi kartı"], correct: 1 },
          { question: "Korhan: ...yanımda o kadar ____ para yok.", options: ["taksitli", "nakit", "kredi kartı", "vade farkı"], correct: 1 },
          { question: "Satıcı: ____ ile tek seferde ödemeniz de mümkün, aynı indirimi yapıyoruz.", options: ["Nakit", "Taksitli", "Kredi kartı", "Vade farkı"], correct: 2 },
          { question: "Korhan: Peki, ____ ödemeler kaç aydan başlıyor?", options: ["peşin", "nakit", "taksitli", "vade farkı"], correct: 2 },
          { question: "Satıcı: ...Hem de peşin fiyatına. Yani ____ yok.", options: ["nakit", "kredi kartı", "taksitli", "vade farkı"], correct: 3 },
        ],
      },
      {
        name: "Cooking Methods (Pişirme Yöntemleri)",
        questions: [
          { question: "Kızartma → ____ → ____", options: ["su → tencere", "yağ → tava", "buhar → fırın", "kömür → mangal"], correct: 1 },
          { question: "Haşlama → ____ → ____", options: ["kömür → mangal", "su → tencere", "buhar → fırın", "yağ → tava"], correct: 1 },
          { question: "Buğulama → ____ → ____", options: ["kömür → mangal", "su → tencere", "buhar → fırın", "yağ → tava"], correct: 2 },
          { question: "Izgara → ____ → ____", options: ["su → tencere", "buhar → fırın", "yağ → tava", "kömür → mangal"], correct: 3 },
        ],
      },
      {
        name: "Health Advice (Sağlık Önerileri)",
        questions: [
          { question: "Dengeli beslenin.", options: ["Alkolü, kafeini, beyaz unu ve tuzu ölçülü tüketin.", "Az yiyin. Kalori ihtiyacınızı farklı besinlerden karşılayın. Hayvansal yağları daha az, zeytinyağını daha çok kullanın.", "Sigara içmeyin. Sigara dumanından uzak durun."], correct: 1 },
          { question: "Damar sağlığınıza dikkat edin.", options: ["Yeni şeyler öğrenin. Yeni bir dil, yeni bir hobi, yeni bir oyun için şansınızı deneyin.", "Gereksiz yere ve yüksek dozda ilaç kullanmayın.", "Kan değerlerinizi, özellikle kolestrolünüzü dikkatle izleyin. Tansiyonunuzu kontrol altında tutun. Daha çok egzersiz yapın, daha az strese girin."], correct: 2 },
          { question: "Bağışıklık sisteminizi güçlendirin.", options: ["Gerekli aşılarınızı (Hepatit, zatürree, grip vs..) yaptırın. Düzenli uyku, egzersiz ve dinlence bağışıklık sisteminizi güçlendirir.", "Dişlerinizi düzenli fırçalayın. 6-8 ayda bir diş hekiminize uğrayın.", "Düzenli olarak kontrol yaptırın. Doktorunuzun önerilerini uygulayın."], correct: 0 },
          { question: "Kötü şeyleri az tüketin.", options: ["Sigara içmeyin. Sigara dumanından uzak durun.", "Az yiyin. Kalori ihtiyacınızı farklı besinlerden karşılayın.", "Alkolü, kafeini, beyaz unu ve tuzu ölçülü tüketin."], correct: 2 },
          { question: "Sigaradan ve dumanından sakının.", options: ["Gereksiz yere ve yüksek dozda ilaç kullanmayın.", "Sigara içmeyin. Sigara dumanından uzak durun.", "Kan değerlerinizi dikkatle izleyin."], correct: 1 },
          { question: "Kas ve kemiklerinizi takviye edin.", options: ["Düzenli egzersiz yapın ve hareketli yaşayın. Yeterli miktarda kalsiyum ve D vitamini alın.", "Dişlerinizi düzenli fırçalayın. 6-8 ayda bir diş hekiminize uğrayın.", "Yeni şeyler öğrenin. Yeni bir dil, yeni bir hobi deneyin."], correct: 0 },
          { question: "Ağız bakımınıza özen gösterin.", options: ["Yeni şeyler öğrenin. Yeni bir dil, yeni bir hobi deneyin.", "Dişlerinizi düzenli fırçalayın. 6-8 ayda bir diş hekiminize uğrayın.", "Düzenli olarak kontrol yaptırın."], correct: 1 },
          { question: "Belleğinizi güçlü tutun.", options: ["Yeni şeyler öğrenin. Yeni bir dil, yeni bir hobi, yeni bir oyun için şansınızı deneyin.", "Alkolü, kafeini, beyaz unu ve tuzu ölçülü tüketin.", "Gereksiz yere ve yüksek dozda ilaç kullanmayın."], correct: 0 },
          { question: "Gereksiz yere ilaç kullanmayın.", options: ["Düzenli olarak kontrol yaptırın. Doktorunuzun önerilerini uygulayın.", "Sigara içmeyin. Sigara dumanından uzak durun.", "Gereksiz yere ve yüksek dozda ilaç kullanmayın."], correct: 2 },
          { question: "Sağlık kontrollerinizi ihmal etmeyin.", options: ["Düzenli olarak kontrol yaptırın. Doktorunuzun önerilerini uygulayın, ilaçlarınızı düzenli kullanın.", "Kan değerlerinizi dikkatle izleyin. Tansiyonunuzu kontrol altında tutun.", "Dişlerinizi düzenli fırçalayın."], correct: 0 },
        ],
      },
      {
        name: "Country Descriptions (Ülke Tanıtımları)",
        questions: [
          { question: "Natalia: Mavi gözlüyüm ve kızıl saç____.", options: ["-sızım", "-lıyım", "-luyum", "-liyim"], correct: 1 },
          { question: "Natalia: Benim ülkemde hava kışın çok soğuk ve kar yağış____.", options: ["-lı", "-sız", "-lü", "-lu"], correct: 0 },
          { question: "Natalia: Ülkem____ ____ ünlü şehir____ Moskova.", options: ["-in / en / -i", "-ın / daha / -ı", "-den / daha / -ı", "-nun / en / -su"], correct: 0 },
          { question: "Chan: Benim ülkem dünya____ en kalabalık ülke____.", options: ["-dan / -dir", "-nın / -sidir", "-dan daha / -dır", "-nın / -sıdır"], correct: 1 },
          { question: "Chan: Ülkemde bir milyar____ fazla insan yaşıyor.", options: ["-dan", "-den", "-ın", "-in"], correct: 0 },
          { question: "Carmen: Akdeniz____ en sıcak ülke____ yaşıyorum.", options: ["-in / -sinde", "-den / -de", "-in / -si", "-den / -ye"], correct: 0 },
          { question: "Carmen: Şarap____ dansı seviyor musunuz?", options: ["-tan daha", "-ı ve", "-sız", "-lı"], correct: 1 },
        ],
      },
    ],
  },
  {
    id: "a1-unit6",
    name: "A1 — Unit 6",
    sections: [
      {
        name: "Daily Life Vocabulary (Günlük Hayat)",
        questions: [
          { question: "Ev ____, banka işlemleri, kimlik işlemleri, faturaları yatırmak...", options: ["öğrenmek", "kiralamak", "oluyorum", "ödüyorum"], correct: 1 },
          { question: "...önemli yerlerin adreslerini, telefonlarını ____ hiç kolay olmuyor.", options: ["kiralamak", "ödüyorum", "öğrenmek", "randevularımı"], correct: 2 },
          { question: "Artık faturalarımı kendim ____,", options: ["oluyorum", "kiralamak", "ödüyorum", "randevularımı"], correct: 2 },
          { question: "...doktor ____ kendim alıyorum.", options: ["öğrenmek", "oluyorum", "ödüyorum", "randevularımı"], correct: 3 },
          { question: "Bir kütüphaneye ya da spor merkezine kendim üye ____.", options: ["kiralamak", "ödüyorum", "oluyorum", "öğrenmek"], correct: 2 },
        ],
      },
      {
        name: "Reading Comprehension — İsabel",
        questions: [
          { question: "İsabel Türkiye'ye ____ geldi.", options: ["henüz", "birkaç ay önce", "çok önceden"], correct: 1 },
          { question: "Türkiye'deki ilk günlerini hala ____.", options: ["hatırlıyor", "hiç hatırlamıyor"], correct: 0 },
          { question: "İlk günlerde birçok işi ____ yaptı.", options: ["kolaylıkla", "zorlukla"], correct: 1 },
          { question: "Arkadaşları ____ yardım etti.", options: ["hiç", "hep"], correct: 1 },
          { question: "Biraz Türkçe öğrendi ve hayat onun için artık daha ____.", options: ["zor", "kolay"], correct: 1 },
        ],
      },
      {
        name: "Accusative Case (Belirtme Hali)",
        questions: [
          { question: "Şu ____ bana uzatır mısın?", options: ["tuzluk", "tuzluğu"], correct: 1 },
          { question: "Dün yeni bir ____ aldım.", options: ["bluz", "bluzu"], correct: 0 },
          { question: "Ablam ____ çok iyi yapar.", options: ["makarna salatası", "makarna salatasını"], correct: 0 },
          { question: "Dünkü ____ seyrettin mi? Sonunda ne oldu?", options: ["film", "filmi"], correct: 1 },
          { question: "Hangi ____ biliyorsunuz?", options: ["diller", "dilleri"], correct: 1 },
          { question: "Her akşam yatmadan önce birkaç sayfa ____ okuyorum.", options: ["kitap", "kitabı"], correct: 0 },
          { question: "____ çok aradım. Neredeydin?", options: ["Sen", "Seni"], correct: 1 },
          { question: "____ evde izliyoruz.", options: ["Maç", "Maçı"], correct: 1 },
          { question: "Kapıcı saat 20.30'da ____ topluyor.", options: ["çöpler", "çöpleri"], correct: 1 },
          { question: "Dün akşam konserde liseden bir ____ gördüm.", options: ["arkadaşım", "arkadaşımı"], correct: 1 },
          { question: "____ annen mi ördü?", options: ["Kazağın", "Kazağını"], correct: 1 },
          { question: "Hafta sonu hiç evden çıkmadım, ____ izledim.", options: ["film", "filmi"], correct: 0 },
          { question: "Şimdi son konuşmacımız ____ dinliyoruz.", options: ["Mehmet Öztürk", "Mehmet Öztürk'ü"], correct: 1 },
          { question: "Babam ____ boyuyor.", options: ["bahçenin kapısı", "bahçenin kapısını"], correct: 1 },
        ],
      },
      {
        name: "Word Associations (Kelime Eşleştirme)",
        questions: [
          { question: "Son ödeme tarihi → ____", options: ["banka", "fatura", "sigorta", "apartman"], correct: 1 },
          { question: "Para çekmek → ____", options: ["hastane", "banka", "restoran", "kütüphane"], correct: 1 },
          { question: "Üye olmak → ____", options: ["kütüphane", "havaalanı", "sigorta", "apartman"], correct: 0 },
          { question: "Acil servis → ____", options: ["restoran", "havaalanı", "hastane", "banka"], correct: 2 },
          { question: "Sipariş vermek → ____", options: ["apartman", "restoran", "kütüphane", "hastane"], correct: 1 },
          { question: "Rötar → ____", options: ["sigorta", "pasaport", "havaalanı", "banka"], correct: 2 },
          { question: "Prim → ____", options: ["apartman", "uçak bileti", "pasaport", "sigorta"], correct: 3 },
          { question: "Uyruk → ____", options: ["pasaport", "sigorta", "fatura", "havaalanı"], correct: 0 },
          { question: "Gidiş-dönüş → ____", options: ["restoran", "apartman", "uçak bileti", "banka"], correct: 2 },
          { question: "Aidat → ____", options: ["sigorta", "kütüphane", "hastane", "apartman"], correct: 3 },
        ],
      },
      {
        name: "Traffic Accident (Trafik Kazası)",
        questions: [
          { question: "Ben de işyerime doğru ____ .", options: ["şerit", "yola çıktım", "rapor tuttum", "ifade aldım"], correct: 1 },
          { question: "Adama ____ için hemen frene bastım...", options: ["çarpmamak", "hasar", "tamir ettirmek", "şikayetçi olmak"], correct: 0 },
          { question: "O sırada trafik polisi geldi. ____.", options: ["İfade aldı", "Şikayetçi oldu", "Rapor tuttu", "Tamir ettirdi"], correct: 2 },
          { question: "...ve bir ____. Bu kazada kesinlikle ____ hatalıydı.", options: ["ifade aldı / karşı taraf", "rapor tuttu / poliçe", "şikayetçi oldu / hasar", "yola çıktı / şerit"], correct: 0 },
          { question: "Yine de ben ondan ____.", options: ["tamir ettirdim", "rapor tuttum", "şikayetçi olmadım", "ifade aldım"], correct: 2 },
          { question: "Arabada da önemli bir ____ yoktu.", options: ["poliçe", "şerit", "hasar", "kasko"], correct: 2 },
          { question: "Ayrıca arabam ____.", options: ["kaskoluydu", "şerit", "poliçe", "hasar"], correct: 0 },
          { question: "Akşam işten çıktıktan sonra tamircide arabamı ____.", options: ["rapor tuttum", "tamir ettirdim", "ifade aldım", "yola çıktım"], correct: 1 },
          { question: "Çünkü kasko ____ süresi dolmuştu.", options: ["hasar", "şerit", "poliçe", "karşı taraf"], correct: 2 },
        ],
      },
      {
        name: "Reading Comprehension — Trafik Kazası",
        questions: [
          { question: "İşe gitmek için neye bindim?", options: ["arabaya", "kamyona", "taksiye"], correct: 0 },
          { question: "Adama çarpmamak için neye bastım?", options: ["yere", "frene", "arabaya"], correct: 1 },
          { question: "Trafik polisi neyi inceledi?", options: ["olay yerini", "kaza raporunu", "arabaları"], correct: 0 },
          { question: "Ben kimden şikayetçi olmadım?", options: ["adamdan", "polisten", "tamirciden"], correct: 0 },
          { question: "Tamircinin parasını kim ödedi?", options: ["adam", "ben", "sigorta"], correct: 1 },
        ],
      },
      {
        name: "Where Do You Go? (Nereye Gidersiniz?)",
        questions: [
          { question: "Hırsızı gördünüz mü? Nasıl biriydi?", options: ["Emniyet Müdürlüğü", "Karakol", "Anahtarcı"], correct: 1 },
          { question: "Oturma iznimin süresi bitti. Uzatmak istiyorum.", options: ["Postane", "Karakol", "Emniyet Müdürlüğü"], correct: 2 },
          { question: "– Dolsun mu? – Hayır, 50 liralık yeter.", options: ["Döviz bürosu", "Benzin istasyonu", "Banka"], correct: 1 },
          { question: "Hafta sonu apartmanımızda su akmadı. Sorun nedir acaba?", options: ["Elektrik İdaresi", "Nakliye şirketi", "Sular İdaresi"], correct: 2 },
          { question: "Hesap cüzdanım yok, maalesef. Ama banka kartım var.", options: ["Döviz bürosu", "Banka", "Postane"], correct: 1 },
          { question: "Benim adıma bir paket geldi mi acaba?", options: ["Postane", "Kargo", "Nakliye şirketi"], correct: 1 },
          { question: "Muayene olmak istiyorum. Ne zaman geleyim?", options: ["Güzellik salonu", "Hastane", "Kuaför"], correct: 1 },
          { question: "Yosun banyomuzu gördünüz mü? Tavsiye ederim.", options: ["Kuaför", "Hastane", "Güzellik salonu"], correct: 2 },
          { question: "Japon Yeni almak istiyorum.", options: ["Banka", "Döviz bürosu", "Postane"], correct: 1 },
          { question: "Sakal tıraşı olmak istiyorum.", options: ["Güzellik salonu", "Hastane", "Kuaför"], correct: 2 },
          { question: "Karanlıkta kaldık.", options: ["Sular İdaresi", "Anahtarcı", "Elektrik İdaresi"], correct: 2 },
          { question: "Çilingir servisiniz var mı? Sokakta kaldık.", options: ["Anahtarcı", "Karakol", "Nakliye şirketi"], correct: 0 },
          { question: "Amerika'ya mektup kaç günde gidiyor?", options: ["Kargo", "Nakliye şirketi", "Postane"], correct: 2 },
          { question: "Evden eve taşıma ücretiniz ne kadar?", options: ["Nakliye şirketi", "Kargo", "Postane"], correct: 0 },
        ],
      },
      {
        name: "Formal Present Tense (-mEktE)",
        questions: [
          { question: "Olimpiyat oyunlarına dört yılda bir farklı ülkelerden binlerce sporcu katılıyor. → Resmi form?", options: ["katılmakta", "katılmaktayız", "katılmaktalar", "katılmaktasınız"], correct: 0 },
          { question: "UNICEF çocuk hakları, sağlık ve eğitimle ilgili çalışmalar yapıyor. → Resmi form?", options: ["yapmakta", "yapmaktayım", "yapmaktasın", "yapmaktalar"], correct: 0 },
          { question: "Türkiye'ye en çok Avrupa ülkelerinden turist geliyor. → Resmi form?", options: ["gelmekteyiz", "gelmekte", "gelmekteler", "gelmektesiniz"], correct: 1 },
        ],
      },
      {
        name: "de/da: Suffix vs. Conjunction",
        questions: [
          { question: "Adam: Evet biliyorum, çünkü (1)____ (2)____ oturuyorum.", options: ["bende / orada", "ben de / orada", "bende / ora da", "ben de / ora da"], correct: 1 },
          { question: "Adam: Aaa, benim (3)____ o (4)____. Hangi daire?", options: ["dairemde / bina da", "dairem de / bina da", "dairemde / binada", "dairem de / binada"], correct: 3 },
          { question: "Kurye: Bu paketin (5)____ 'Can Yıldız' yazıyor.", options: ["üstünde", "üstün de", "bende", "zarfta"], correct: 0 },
          { question: "Adam: O zaman bu paket sizin, ayrıca bu (6)____.", options: ["zarfta", "zarf da", "bende", "orada"], correct: 1 },
        ],
      },
      {
        name: "-ki Suffix (Relative Suffix)",
        questions: [
          { question: "Dün akşam bir film seyrettim. Çok komikti. → Birleştirin:", options: ["Dün akşamki film çok komikti.", "Dün akşamdaki film çok komikti.", "Dün akşam filmki çok komikti."], correct: 0 },
          { question: "Yarın bir konser var. O konsere bilet aldım. → Birleştirin:", options: ["Yarınki konsere bilet aldım.", "Yarın konserki bilet aldım.", "Yarındaki konsere bilet aldım."], correct: 0 },
          { question: "Bu sabah toplantıya katıldık. Çok sıkıcıydı. → Birleştirin:", options: ["Bu sabah toplantıki çok sıkıcıydı.", "Bu sabahki toplantı çok sıkıcıydı.", "Bu sabahta ki toplantı çok sıkıcıydı."], correct: 1 },
          { question: "Öğlen bir randevum vardı. Onu iptal ettim. → Birleştirin:", options: ["Öğlenki randevumu iptal ettim.", "Öğlendeki randevumu iptal ettim.", "Öğlen randevumki iptal ettim."], correct: 0 },
          { question: "Müdürle bugün görüşmem var. Bu görüşme çok önemli. → Birleştirin:", options: ["Müdürle bugün görüşmeki çok önemli.", "Müdürle bugünkü görüşme çok önemli.", "Müdürle bugündeki görüşme çok önemli."], correct: 1 },
          { question: "Gazetede dün bir haber vardı. Onu okudunuz mu? → Birleştirin:", options: ["Gazeteki dünkü haberi okudunuz mu?", "Gazetedeki haberi okudunuz mu?", "Dünkü gazeteki haberi okudunuz mu?"], correct: 1 },
          { question: "Salı günü sınav var. Ona geç kalmayın. → Birleştirin:", options: ["Salı gününki sınava geç kalmayın.", "Salıdaki sınava geç kalmayın.", "Salı günkü sınava geç kalmayın."], correct: 2 },
          { question: "Geçen gece fırtına çıktı. O fırtınada salonun camı kırıldı. → Birleştirin:", options: ["Geçen gecedeki fırtınada salonun camı kırıldı.", "Geçen geceki fırtınada salonun camı kırıldı.", "Geçen gece fırtınaki salonun camı kırıldı."], correct: 1 },
          { question: "Bu duraktan sonra bir durak var. O durakta iniyorum. → Birleştirin:", options: ["Sonraki durakta iniyorum.", "Sonradaki durakta iniyorum.", "Bu duraktanki sonra iniyorum."], correct: 0 },
          { question: "Bu grubun konserlerini daha önce de izledim. O konserler bu kadar kalabalık değildi. → Birleştirin:", options: ["Daha öncedeki konserler bu kadar kalabalık değildi.", "Daha önceki konserler bu kadar kalabalık değildi.", "Daha önce konserlerki bu kadar kalabalık değildi."], correct: 1 },
          { question: "Şimdi çocuklar her şeyi biliyor. Onlar çok akıllı. → Birleştirin:", options: ["Şimdideki çocuklar çok akıllı.", "Şimdi çocuklarki çok akıllı.", "Şimdiki çocuklar çok akıllı."], correct: 2 },
          { question: "Geçmişte bazı hatalar yaptım. O hatalardan ders aldım. → Birleştirin:", options: ["Geçmişteki hatalarımdan ders aldım.", "Geçmişki hatalarımdan ders aldım.", "Geçmişte hatalarki ders aldım."], correct: 0 },
          { question: "Gelecek yıl projeler yapmak istiyoruz. O projeler şirketimiz için çok önemli. → Birleştirin:", options: ["Gelecek yıldaki projeler şirketimiz için çok önemli.", "Gelecek yılki projeler şirketimiz için çok önemli.", "Gelecekki yıl projeler şirketimiz için çok önemli."], correct: 1 },
          { question: "Günümüzde birçok teknolojik alet kullanıyoruz. Bu aletler hayatımızı kolaylaştırıyor. → Birleştirin:", options: ["Günümüzki teknolojik aletler hayatımızı kolaylaştırıyor.", "Günümüzdeki teknolojik aletler hayatımızı kolaylaştırıyor.", "Günümüzde aletlerki hayatımızı kolaylaştırıyor."], correct: 1 },
          { question: "Şimdi sırada bir şarkı var. Bu şarkıyı Ayşe ve Murat için çalıyoruz. → Birleştirin:", options: ["Sıradaki şarkıyı Ayşe ve Murat için çalıyoruz.", "Sıraki şarkıyı Ayşe ve Murat için çalıyoruz.", "Şimdiki sırada şarkıyı Ayşe ve Murat için çalıyoruz."], correct: 0 },
        ],
      },
      {
        name: "-ki Fill in the Blank",
        questions: [
          { question: "____ derste ne yaptınız?", options: ["Önceki", "Sonraki", "Bugünkü", "Yarınki"], correct: 0 },
          { question: "Dün ____ yemeği beğendin mi?", options: ["öğlenki", "akşamki", "sabahki", "dünkü"], correct: 1 },
          { question: "Saat 13.30'daki uçağı kaçırdınız. – ____ uçak ne zaman?", options: ["yarınki", "bugünkü", "sonraki", "geçen haftaki"], correct: 2 },
          { question: "____ partiye geliyor musun?", options: ["bugünkü", "dünkü", "yarınki", "geçen haftaki"], correct: 2 },
          { question: "Sence bu ayakkabı nasıl oldu? – ____ daha iyiydi.", options: ["sonraki", "geçen seferki", "bugünkü", "dünkü"], correct: 1 },
          { question: "Toplantı saat kaçta? – ____ gibi saat onda.", options: ["her günkü", "her zamanki", "sabahki", "bugünkü"], correct: 1 },
          { question: "Ben ____ filmi hiç beğenmedim. – Ben de. ____ daha iyiydi.", options: ["dünkü / geçen haftaki", "bugünkü / yarınki", "bu ayki / önceki", "dün geceki / sabahki"], correct: 0 },
          { question: "Lütfen tam zamanında gel. ____ gibi geç kalma.", options: ["her zamanki", "her günkü", "geçmişteki", "bugünkü"], correct: 1 },
          { question: "Çok merak ediyorum. ____ binalar nasıl olacak.", options: ["geçmişteki", "bugünkü", "gelecekteki", "bu ayki"], correct: 2 },
          { question: "Uykusuz görünüyorsun. – Evet, ____ gibi bu sabah da erken kalktım.", options: ["sabahki", "dün geceki", "her zamanki", "öğlenki"], correct: 2 },
        ],
      },
    ],
  },
];
